### PR TITLE
Fix rotation example

### LINKED ISSUE #130: Transforming Lines example not showing anything
The 2 examples in this link look so much alike. I thought the idea was to show the translation distinctly. 

https://simondanisch.github.io/ReferenceImages/gallery/transforming_lines/index.html

### PR DESCRIPTION
**Pull request by asinghvi17**
Fixes #130 
Supercedes #134

### CODE REVIEW

File: examples/examples2d.jl [hunk 1]
```diff
@@ -699,6 +699,7 @@ end
     @cell "Transforming lines" [transformation, lines] begin
         N = 7 # number of colours in default palette
         sc = Scene()
+        st = Stepper(sc. @replace_with_a_path)
```
Comment (asinghvi17) [inline examples/examples2d.jl]:
```suggestion
        st = Stepper(sc, @replace_with_a_path)
